version: 2.1

orbs:
  cli: circleci/circleci-cli@0.1.1
  orb-tools: circleci/orb-tools@2.0.2

workflows:
  git:
    jobs:
      - git-schema-validation
      - git-publish-sha:
          requires:
            - git-schema-validation
      - git-integration-test:
          requires:
            - git-publish-sha
  yarn:
    jobs:
      - yarn-schema-validation
      - yarn-publish-sha:
          requires:
            - yarn-schema-validation
      - yarn-integration-test:
          requires:
            - yarn-publish-sha

jobs:
  git-schema-validation:
    executor: cli/default
    steps:
      - checkout
      - orb-tools/validate:
          orb-path: src/git/orb.yml
  git-publish-sha:
    executor: cli/default
    steps:
      - checkout
      - orb-tools/publish:
          orb-path: src/git/orb.yml
          orb-ref: mavenlink/git@dev:$CIRCLE_SHA1
          token-variable: $ORB_PUBLISHING_TOKEN
  git-integration-test:
    machine:
      image: circleci/classic:latest
    steps:
      - cli/install
      - checkout
      - run: cp -r ~/.ssh ~/project
      - run: git add --all
      - run: sed -i -e 's/$CIRCLE_SHA1/'$CIRCLE_SHA1'/g' src/git/config.yml
      - run: circleci config process src/git/config.yml > src/git/processed_config.yml
      - run: circleci local execute -c src/git/processed_config.yml | tee local_build_output.txt /dev/stderr | tail -n 1 | grep "Success"
  yarn-schema-validation:
    executor: cli/default
    steps:
      - checkout
      - orb-tools/validate:
          orb-path: src/yarn/orb.yml
  yarn-publish-sha:
    executor: cli/default
    steps:
      - checkout
      - orb-tools/publish:
          orb-path: src/yarn/orb.yml
          orb-ref: mavenlink/yarn@dev:$CIRCLE_SHA1
          token-variable: $ORB_PUBLISHING_TOKEN
  yarn-integration-test:
    machine:
      image: circleci/classic:latest
    steps:
      - cli/install
      - checkout
      - run: sed -i -e 's/$CIRCLE_SHA1/'$CIRCLE_SHA1'/g' src/yarn/config.yml
      - run: circleci config process src/yarn/config.yml > src/yarn/processed_config.yml
      - run: circleci local execute -c src/yarn/processed_config.yml | tee local_build_output.txt /dev/stderr | tail -n 1 | grep "Success"
